#!/bin/sh
PROJECT_NAME=LayerSlack
if [ -z $S3_BUCKET ]; then
    . ./parameter.cfg
fi
if [ -z $REGION ]; then
    . ./parameter.cfg
fi
rm -rf .aws-sam
rm -rf lib/python
mkdir -p lib/python
cp -r Slack lib/python
sam build
cd .aws-sam/build
aws cloudformation package \
    --region $REGION \
    --template-file template.yaml \
    --s3-prefix $PROJECT_NAME \
    --s3-bucket $S3_BUCKET \
    --output-template-file packaged.yaml
aws cloudformation deploy \
    --stack-name $PROJECT_NAME \
    --template-file packaged.yaml \
    --region $REGION \
    --capabilities CAPABILITY_NAMED_IAM  \
    --s3-bucket $S3_BUCKET \
    --s3-prefix $PROJECT_NAME \
