#!/bin/sh
. ./parameter.cfg
rm -rf .aws-sam
rm -rf ./lib/python/*
pip install -t ./lib/python/ -r requirements.txt
cd .aws-sam/build
aws cloudformation package \
    --region $REGION \
    --template-file template.yaml \
    --s3-prefix $PROJECT_NAME \
    --s3-bucket $S3_BUCKET \
    --output-template-file packaged.yaml
aws cloudformation deploy \
    --stack-name $PROJECT_NAME \
    --template-file packaged.yaml \
    --region $REGION \
    --capabilities CAPABILITY_NAMED_IAM  \
    --s3-bucket $S3_BUCKET \
    --s3-prefix $PROJECT_NAME \
